version: '3.8'

services:
  # Unit 2 Backend
  backend-unit2:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: iot-backend-unit2-dev
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - UNIT_NAME=unit2
      - UNIT_NUMBER=2
      - UNIT_DOMAIN=unit2htr.system
      - UNIT_SUBNET=30
      - HTR_A_IP=192.168.30.29
      - HTR_A_DEVICE_ID=[0;34m[INFO][0m Attempting to discover IO-Link device ID from HTR-A at 192.168.30.29...
[0;34m[INFO][0m Using automated discovery tool...
[0;34m[INFO][0m Running automated device ID discovery...
[0;32m[SUCCESS][0m ✅ Device ID automatically discovered: 🔍 IO-Link Device Discovery for 192.168.30.29
==================================================
✅ Network connectivity OK
🔍 Attempting to discover device ID from 192.168.30.29...
❌ Could not automatically discover device ID
📋 Please manually enter the device ID from the IO-Link master's web interface
[0;36m[INPUT][0m Use this device ID? (Y/n):
🔍 IO-Link Device Discovery for 192.168.30.29
==================================================
✅ Network connectivity OK
🔍 Attempting to discover device ID from 192.168.30.29...
❌ Could not automatically discover device ID
📋 Please manually enter the device ID from the IO-Link master's web interface
      - HTR_A_TEMP_PORT=6
      - HTR_A_TEMP_TOPIC=instrument/unit2/htr_a/temperature
      - HTR_B_IP=192.168.30.33
      - HTR_B_DEVICE_ID=[0;34m[INFO][0m Attempting to discover IO-Link device ID from HTR-B at 192.168.30.33...
[0;34m[INFO][0m Using automated discovery tool...
[0;34m[INFO][0m Running automated device ID discovery...
[0;32m[SUCCESS][0m ✅ Device ID automatically discovered: 🔍 IO-Link Device Discovery for 192.168.30.33
==================================================
❌ Cannot reach the device. Please check:
  1. Device is powered on
  2. Network cable is connected
  3. IP address is correct
  4. Device is on the same network
[0;36m[INPUT][0m Use this device ID? (Y/n):
🔍 IO-Link Device Discovery for 192.168.30.33
==================================================
❌ Cannot reach the device. Please check:
  1. Device is powered on
  2. Network cable is connected
  3. IP address is correct
  4. Device is on the same network
      - HTR_B_TEMP_PORT=6
      - HTR_B_TEMP_TOPIC=instrument/unit2/htr_b/temperature
      - DATABASE_URL=postgresql://iotuser:iotpassword@database:5432/iotdata
      - LOG_LEVEL=DEBUG
    ports:
      - "38201:8000"
    volumes:
      - ./backend/src:/app/src
      - ./config:/app/config
    depends_on:
      - mqtt
      - database
    networks:
      - iot-network

  # Unit 2 Frontend
  frontend-unit2:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: iot-frontend-unit2-dev
    environment:
      - VITE_MQTT_HOST=mqtt
      - VITE_MQTT_PORT=1883
      - VITE_MQTT_WS_PORT=9001
      - VITE_UNIT_NAME=unit2
      - VITE_UNIT_NUMBER=2
      - VITE_UNIT_DOMAIN=unit2htr.system
      - VITE_UNIT_SUBNET=30
      - VITE_HTR_A_IP=192.168.30.29
      - VITE_HTR_A_DEVICE_ID=[0;34m[INFO][0m Attempting to discover IO-Link device ID from HTR-A at 192.168.30.29...
[0;34m[INFO][0m Using automated discovery tool...
[0;34m[INFO][0m Running automated device ID discovery...
[0;32m[SUCCESS][0m ✅ Device ID automatically discovered: 🔍 IO-Link Device Discovery for 192.168.30.29
==================================================
✅ Network connectivity OK
🔍 Attempting to discover device ID from 192.168.30.29...
❌ Could not automatically discover device ID
📋 Please manually enter the device ID from the IO-Link master's web interface
[0;36m[INPUT][0m Use this device ID? (Y/n):
🔍 IO-Link Device Discovery for 192.168.30.29
==================================================
✅ Network connectivity OK
🔍 Attempting to discover device ID from 192.168.30.29...
❌ Could not automatically discover device ID
📋 Please manually enter the device ID from the IO-Link master's web interface
      - VITE_HTR_A_TOPIC=instrument/unit2/htr_a/temperature
      - VITE_HTR_B_IP=192.168.30.33
      - VITE_HTR_B_DEVICE_ID=[0;34m[INFO][0m Attempting to discover IO-Link device ID from HTR-B at 192.168.30.33...
[0;34m[INFO][0m Using automated discovery tool...
[0;34m[INFO][0m Running automated device ID discovery...
[0;32m[SUCCESS][0m ✅ Device ID automatically discovered: 🔍 IO-Link Device Discovery for 192.168.30.33
==================================================
❌ Cannot reach the device. Please check:
  1. Device is powered on
  2. Network cable is connected
  3. IP address is correct
  4. Device is on the same network
[0;36m[INPUT][0m Use this device ID? (Y/n):
🔍 IO-Link Device Discovery for 192.168.30.33
==================================================
❌ Cannot reach the device. Please check:
  1. Device is powered on
  2. Network cable is connected
  3. IP address is correct
  4. Device is on the same network
      - VITE_HTR_B_TOPIC=instrument/unit2/htr_b/temperature
      - VITE_API_BASE_URL=http://backend-unit2:8000
      - NODE_ENV=development
    ports:
      - "33201:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - mqtt
      - backend-unit2
    networks:
      - iot-network
