version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: cursor-mqtt-broker
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=iotuser
      - POSTGRES_PASSWORD=iotpassword
      - POSTGRES_DB=iotdata
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - DB_HOST=timescaledb
      - DB_USER=iotuser
      - DB_PASSWORD=iotpassword
      - DB_NAME=iotdata
    depends_on:
      - mqtt-broker
      - timescaledb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: iot-control-frontend
    ports:
      - "3000:3000"
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
    depends_on:
      - mqtt-broker
    restart: unless-stopped

  mqtt-test-publisher:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    init: true  # Use tini as init process
    command: python -u src/mqtt_temp_publisher.py  # -u for unbuffered output
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - PYTHONUNBUFFERED=1
    depends_on:
      mqtt-broker:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[p]ython.*mqtt_temp_publisher' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-log:
  timescaledb-data: 