apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-control-config
  namespace: iot-control
data:
  # IO-Link Configuration (from backup notes)
  iolink_config.yml: |
    devices:
      temperature_sensor:
        master_ip: "192.168.30.29"
        port: 6
        mqtt_topic: "iolink/#"
        data_type: "temperature"
        unit: "celsius"
        update_rate: 1000
        scaling_factor: 0.1
  
  # MQTT Configuration
  mqtt_config.yml: |
    broker:
      host: "mqtt-service"
      port: 1883
      ws_port: 9001
    topics:
      temperature_processed: "instruments_ti"
      temperature_raw: "instrument/htr_a"
      iolink_debug: "iolink/#"
      unit1_temperature: "instrument/unit1/temperature"
      unit2_temperature: "instrument/unit2/temperature"
  
  # Device Configuration (from backup notes)
  device_config.yml: |
    devices:
      htr_a:
        device_id: "00-02-01-6D-55-8A"
        max_temp: 1200
        name: "HTR-A"
        description: "Primary Heater Control"
        ip: "192.168.30.29"
        input_device_id: null
        iolink_ports:
          section_1: "port[1]/iolinkdevice/pdout"
          section_2: "port[2]/iolinkdevice/pdout"
          section_3: "port[3]/iolinkdevice/pdout"
          section_4: "port[4]/iolinkdevice/pdout"
          pid_pulse: "port[5]/iolinkdevice/pdout"
          temp_sensor: "port[6]/iolinkdevice/pdin"
      htr_b:
        device_id: "00-02-01-6D-55-86"
        max_temp: 800
        name: "HTR-B"
        description: "Secondary Heater Control"
        ip: "192.168.30.33"
        input_device_id: "00-02-01-6d-55-86"
        iolink_ports:
          section_1: "port[1]/iolinkdevice/pdout"
          section_2: "port[2]/iolinkdevice/pdout"
          section_3: "port[3]/iolinkdevice/pdout"
          section_4: "port[4]/iolinkdevice/pdout"
          pid_pulse: "port[5]/iolinkdevice/pdout"
          temp_sensor: "port[6]/iolinkdevice/pdin"
  
  # Frontend Environment Configuration
  frontend_env.yml: |
    # MQTT Configuration
    VITE_MQTT_HOST: "mqtt-service"
    VITE_MQTT_PORT: "1883"
    VITE_MQTT_WS_PORT: "9001"
    VITE_MQTT_WS_PATH: "/mqtt"
    
    # Unit 1 Configuration
    VITE_HTR_A_IP: "192.168.30.29"
    VITE_HTR_A_DEVICE_ID: "00-02-01-6D-55-8A"
    VITE_HTR_A_TOPIC: "instrument/unit1/temperature"
    VITE_UNIT_NAME: "unit1"
    
    # Unit 2 Configuration
    VITE_HTR_B_IP: "192.168.30.33"
    VITE_HTR_B_DEVICE_ID: "00-02-01-6D-55-86"
    VITE_HTR_B_TOPIC: "instrument/unit2/temperature"
    
    # API Configuration
    VITE_API_BASE_URL: "http://backend-service:8000"
    VITE_WS_BASE_URL: "ws://backend-service:8000" 