apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-data-pv
  namespace: iot-control
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mqtt
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-log-pv
  namespace: iot-control
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mqtt-logs
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: iot-control
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/timescaledb
  storageClassName: local-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: iot-control
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 