apiVersion: v1
kind: Secret
metadata:
  name: iot-control-secrets
  namespace: iot-control
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  mqtt_username: bW9xdXR0dXNlcg==  # mqttuser
  mqtt_password: bW9xdXR0cGFzc3dvcmQ=  # mqttpassword
  database_url: cG9zdGdyZXNxbDovL2lvdHVzZXI6aW90cGFzc3dvcmRAZGF0YWJhc2Utc2VydmljZTowMDAwL2lvdGRhdGE=  # postgresql://iotuser:iotpassword@database-service:0000/iotdata
  database_user: aW90dXNlcg==  # iotuser
  database_password: aW90cGFzc3dvcmQ=  # iotpassword
  database_name: aW90ZGF0YQ==  # iotdata
---
apiVersion: v1
kind: Secret
metadata:
  name: iolink-credentials
  namespace: iot-control
type: Opaque
data:
  # IO-Link master credentials (if required)
  iolink_username: YWRtaW4=  # admin
  iolink_password: YWRtaW4=  # admin 